// TodoVueJs/src/components/Todo.vue
<script>
import TodoModel from '../scripts/TodoModel';


export default {


    props: {
        'todo':Object,
        'search':String,
    }
    ,

    data(){
        return {
            id:this.$props.todo.id,
            title:this.$props.todo.title,
            description:this.$props.todo.description,
            dueAt:this.$props.todo.due_at && new Date(this.$props.todo.due_at),
            doneAt:this.$props.todo.done_at && new Date(this.$props.todo.done_at),

            createdAt:this.$props.todo.created_at && new Date(this.$props.todo.created_at),
            updatedAt:this.$props.todo.updated_at && new Date(this.$props.todo.updated_at),

            shownExactTime: false,
            searchText:this.search,
        }
    },

    computed:{
        status(){
            
            console.log('status:',this.doneAt,!!this.doneAt);
            return !!this.doneAt;
        },
        lastEdit(){
            return this.dateToString(this.updatedAt || this.createdAt);
        },
        dueAtStr(){
            return this.dateToString(this.dueAt);
        },
        lastDoneAt(){
            return this.dateToString(this.doneAt);
        },
        getTitle(){
            if(this.title!='')
                this.title = this.title.split(' ').map(word=>word[0].toUpperCase()+word.slice(1)).join(' ');
            if(this.searchText == null)
                return this.title;
            return this.styleSearchArea(this.title);
        },
        getEditLink(){
            return `/edit/${this.id}`;
        }
    },

    methods:{
        toggleStatus(){
            this.doneAt = this.doneAt? null: new Date();
            this.$emit('change-todo-status', this.todo, this.doneAt);
            TodoModel.update(this.id, {done_at: this.doneAt});

        },
        dateToString(date, exact=false){
            if(!date) return date;
            exact = this.shownExactTime;
            // console.log(date);
            if(exact)
                return `${date.getFullYear()}/${date.getMonth()+1}/${date.getDate()} ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}`;
            let nowDate = new Date();
            
            let last_edit_out = '';
            switch(true){
                case nowDate.getFullYear() != date.getFullYear():
                    last_edit_out += `${date.getFullYear()}/${date.getMonth()+1}/${date.getDate()}`;
                    break;

                case nowDate.getMonth() != date.getMonth():
                    let diffMonth = nowDate.getMonth() - date.getMonth();
                    last_edit_out += `${Math.abs(diffMonth)} month${Math.abs(diffMonth)>1?'s':''} ${diffMonth<0? 'next':'ago'}`;
                    break;
                
                case nowDate.getDate() != date.getDate():
                    let diffDate = nowDate.getDate() - date.getDate();
                    last_edit_out += `${Math.abs(diffDate)} day${Math.abs(diffDate)>1?'s':''} ${diffDate<0? 'next':'ago'}`;
                    break;

                case nowDate.getHours() != date.getHours():
                    let diffHour = nowDate.getHours() - date.getHours();
                    last_edit_out += `${Math.abs(diffHour)} hour${Math.abs(diffHour)>1?'s':''} ${diffHour<0? 'next':'ago'}`;
                    break;

                case nowDate.getMinutes() != date.getMinutes():
                    let diffMinute = nowDate.getMinutes() - date.getMinutes();
                    last_edit_out += `${Math.abs(diffMinute)} minute${Math.abs(diffMinute)>1?'s':''} ${diffMinute<0? 'next':'ago'}`;
                    break;
                
                case nowDate.getSeconds() != date.getSeconds():
                    let diffSecond = nowDate.getSeconds() - date.getSeconds();
                    last_edit_out += `${Math.abs(diffSecond)} second${Math.abs(diffSecond)>1?'s':''} ${diffSecond<0? 'next':'ago'}`;
                    break;
                
                default:
                    last_edit_out+= 'now';
            }

            return last_edit_out;
        },

        styleSearchArea(text){
            if(!this.searchText)return text;
            if(this.searchText == text)return this.getStyleArea(text, true);

            // this.searchText = this.searchText.toLowerCase();
            let orgText = text;
            
            let regex = new RegExp('('+this.searchText.replaceAll(/\s/g,'').split('').join(').*(')+')','ig');
            let matches = text.matchAll(regex);

            let styledText = '';
            let pastIndex = 0;
            for(const match of matches){
                if(pastIndex===0){
                    pastIndex=match.index;
                    styledText=orgText.slice(0,pastIndex);
                }
                styledText += this.getStyleArea(orgText.slice(pastIndex, pastIndex+=match[0].length));

            }
            styledText+=orgText.slice(pastIndex)
            console.log(regex);
            console.log('#',this.searchText,':',this.title,'#','Style as search..',styledText);
            return styledText;
        },
        
        getStyleArea(text, isExact=false){
            return `<ins class="search-area${isExact?'-exact':''}">${text}</ins>`;
        }

    },

    watch:{
        todo(todo){
            this.id=todo.id;
            this.title=todo.title;
            this.description=todo.description;
            this.dueAt=todo.due_at && new Date(todo.due_at);
            this.doneAt=todo.done_at && new Date(todo.done_at);

            this.createdAt=todo.created_at && new Date(todo.created_at);
            this.updatedAt=todo.updated_at && new Date(todo.updated_at);
        },
        search(newSearch){
            this.searchText = newSearch;
        }
    }


}
</script>

<template>
    <div class="todo-item" @mouseover="this.shownExactTime=true" @mouseout="this.shownExactTime=false">
        <div class="nav">
            <h3 class="title" v-html="getTitle"></h3>

            <div class="settings">
                <div class="delete" title="delete the todo">
                    <i class="fa-regular fa-trash-can fa-3x"></i>
                </div>

                <router-link :to="getEditLink" class="edit" title="edit the todo">
                    <i class="fa-solid fa-pen-to-square fa-3x"></i>
                </router-link>

                <div class="status">
                    <i class="fa-solid fa-hourglass fa-3x"></i>
                </div>
            </div>
        </div>
        
        <p class="description">{{description}}</p>

        <p class="due-at">Due at: {{dueAtStr}}</p>
        <p class="last-edit">Last edit: {{lastEdit}}</p>

        <p :class="{'done-at':true, 'status':true, 'status-done':!!this.doneAt}" @click="toggleStatus()">{{lastDoneAt? 'Done at: '+lastDoneAt:'Waiting to done...'}}</p>
    </div>
</template>

// todo_react_js/src/components/Todo.js
import React from 'react';
import { Link } from 'react-router-dom';
import TodoModel from '../scripts/TodoModel';
import Check from './icons/check';
import DeleteLogo from './icons/trash-can-solid';
import EditLogo from './icons/pen-to-square-solid';

export default class Todo extends React.Component {
    constructor(props){
        super(props);

        this.state = {
            id: this.props.todo.id,
            title: this.props.todo.title,
            description: this.props.todo.description,
            doneAt: this.props.todo.done_at,

            dueAt: this.props.todo.due_at,
            createdAt: this.props.todo.created_at,
            updatedAt: this.props.todo.updated_at,

            shownCloserTime: false,
        };
    }


    toggleStatus(){
        let newDoneAt = this.state.doneAt ? null : new Date().toISOString();
        this.setState({
            doneAt: newDoneAt
        });

        console.log('todomodel@update',this.state.id, newDoneAt);
        TodoModel.update(this.state.id,{
            done_at: newDoneAt
        });

        this.props.todo.done_at = newDoneAt;
        
        this.props.forceUpdate();
    }

    get dueAt(){
        return this.dateToString(new Date(this.state.dueAt));
    }
    get doneAt(){
        return this.dateToString(new Date(this.state.doneAt));
    }
    get lastEditAt(){
        return this.dateToString(new Date(this.state.updatedAt || this.state.createdAt));
    }
    
    showCloserTime(){
        this.setState({
            shownCloserTime: true
        });
    }

    showNearlyTime(){
        this.setState({
            shownCloserTime: false
        });
    }

    dateToString(date, exact = false) {
        if (!date)
            return date;
        exact = this.state.shownCloserTime;
        // console.log(date);
        if (exact)
            return `${date.getFullYear()}/${date.getMonth() + 1}/${date.getDate()} ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}`;
        let nowDate = new Date();
        let last_edit_out = "";
        switch (true) {
            case nowDate.getFullYear() != date.getFullYear():
                last_edit_out += `${date.getFullYear()}/${date.getMonth() + 1}/${date.getDate()}`;
                break;
            case nowDate.getMonth() != date.getMonth():
                let diffMonth = nowDate.getMonth() - date.getMonth();
                last_edit_out += `${Math.abs(diffMonth)} month${Math.abs(diffMonth) > 1 ? "s" : ""} ${diffMonth < 0 ? "next" : "ago"}`;
                break;
            case nowDate.getDate() != date.getDate():
                let diffDate = nowDate.getDate() - date.getDate();
                last_edit_out += `${Math.abs(diffDate)} day${Math.abs(diffDate) > 1 ? "s" : ""} ${diffDate < 0 ? "next" : "ago"}`;
                break;
            case nowDate.getHours() != date.getHours():
                let diffHour = nowDate.getHours() - date.getHours();
                last_edit_out += `${Math.abs(diffHour)} hour${Math.abs(diffHour) > 1 ? "s" : ""} ${diffHour < 0 ? "next" : "ago"}`;
                break;
            case nowDate.getMinutes() != date.getMinutes():
                let diffMinute = nowDate.getMinutes() - date.getMinutes();
                last_edit_out += `${Math.abs(diffMinute)} minute${Math.abs(diffMinute) > 1 ? "s" : ""} ${diffMinute < 0 ? "next" : "ago"}`;
                break;
            case nowDate.getSeconds() != date.getSeconds():
                let diffSecond = nowDate.getSeconds() - date.getSeconds();
                last_edit_out += `${Math.abs(diffSecond)} second${Math.abs(diffSecond) > 1 ? "s" : ""} ${diffSecond < 0 ? "next" : "ago"}`;
                break;
            default:
                last_edit_out += "now";
        }
        return last_edit_out;
    }

    styleSearchArea(text) {
        if (!this.props.searchText)
            return text;
        if (this.props.searchText == text)
            return this.getStyleArea(text, true);
        // this.searchText = this.searchText.toLowerCase();
        let orgText = text;
        let regex = new RegExp("(" + this.props.searchText.replaceAll(/\s/g, "").split("").join(").*?(") + ")", "ig");
        let matches = text.matchAll(regex);
        let styledText = "";
        let pastIndex = 0;
        for (const match of matches) {
            console.log('match:',match);
            if (pastIndex !== match.index) {
                styledText += orgText.slice(pastIndex, pastIndex = match.index);
            }
            styledText += this.getStyleArea(orgText.slice(pastIndex, pastIndex += match[0].length));
        }
        styledText += orgText.slice(pastIndex);
        console.log(regex);
        console.log("#", this.props.searchText, ":", this.title, "#", "Style as search..", styledText);
        return styledText;
    }
    getStyleArea(text, isExact = false) {
        return `<ins class="search-area${(isExact ?"-exact":"")}">${text}</ins>`;
    }

    getTitle(){
        if(!this.props.searchText.trim())
            return this.state.title;
        return this.styleSearchArea(this.state.title);
    }

    deleteTodo(){
        console.log(this.state.id);
        TodoModel.delete(this.state.id);
        this.props.onRequery();
    }

    render(){
        return (
            <div className="todo-item" onMouseOver={this.showCloserTime.bind(this)} onMouseOut={this.showNearlyTime.bind(this)}>
                <div className="nav">
                    <p className="title" dangerouslySetInnerHTML={{__html:this.getTitle()}}></p>
                    <div className="settings">
                        <div className="delete-logo" title="delete the todo" onClick={this.deleteTodo.bind(this)}>
                            <DeleteLogo class="delete-logo"/>
                        </div>

                        {/* <router-link :to="getEditLink" title="edit the todo" :disabled="isDead" @click="onClickEdit">
                            <edit-logo class="edit-logo" />
                        </router-link> */}

                        <Link className="edit-logo" title="edit the todo" to={`/edit/${this.state.id}`}>
                            <EditLogo className="edit-logo"/>
                        </Link>

                        <div className={"status-logo "+(this.state.doneAt && "todo-done")} onClick={this.toggleStatus.bind(this)}>
                            {this.state.doneAt && <Check/>}
                        </div>
                    </div>
                </div>
                <p className="description">{this.state.description}</p>
                <p className="due-at">Due at: {this.dueAt}</p>
                <p className="last-edit">Last edit at: {this.lastEditAt}</p>
                <p className="done-at">{this.state.doneAt? `Done at: ${this.doneAt}`: 'Todo is not done yet!'}</p>
            </div>
        );
    }
}
