// todo_lit/src/views/CreateTodoView.js
import { LitElement, html } from "lit";
import TodoModel from "../scripts/TodoModel";
// import Alert from "../modules/Alert";

export default class CreateTodoView extends LitElement {
    static properties = {
        title:{state:true},
        description:{state:true},
        dueAt:{state:true},
        doneAt:{state:true},

        createdAt:{state:true},
        updatedAt:{state:true},
    };
    constructor(){
        super();
        this.title = null;
        this.description= null;
        this.dueAt = new Date();
        this.doneAt = null;

        this.createdAt = null;
        this.updatedAt = null;
    }

    createTodo(){

        let createdAt = new Date().toISOString();
        this.createdAt = createdAt;

        TodoModel.create({
            title: this.title,
            description: this.description,
            due_at: this.dueAt,
            done_at: this.doneAt,

            created_at: createdAt,
            updated_at: this.updatedAt,
        });

        alert('created!');
    }

    onChangeDue(e){
        let date = new Date();
        date.setTime(new Date(e.target.value).getTime());
        this.dueAt = date;

    }

    render(){
        return html`
        <div>
        <label for="title">title</label>
        <input id="title" placeholder="title" .value=${this.title} @change=${e=>this.title=e.target.value}/>

        <label for="description">description</label>
        <input id="description" placeholder="description" .value=${this.description} @change=${e=>this.description=e.target.value}/>

        <label for="due">due</label>
        <input id="due" placeholder="due" .value=${new Date(this.dueAt).toLocaleDateString('swe')} @change=${this.onChangeDue}/>


        <button @click=${this.createTodo}>Create todo !</button>
        </div>
        `;
    }
}

customElements.define('created-todo-view', CreateTodoView);

// todo_react_js/src/views/CreateTodoView.js
import React from 'react';
import TodoModel from '../scripts/TodoModel';
import Alert from '../modules/Alert/Alert';
import TodoFormCreateSubmitLogo from '../components/icons/todo-form-create-submit-logo';


export default class CreateTodoView extends React.Component{
    constructor(props){
        super(props);

        this.state = {
            title: '',
            description: '',
            dueAt: new Date().toISOString(),
            doneAt: null,

            createdAt: null,
            updatedAt: null,
        };
    }

    createTodo(){

        let createdAt = new Date().toISOString();
        this.setState({
            createdAt,
        });

        TodoModel.create({
            title: this.state.title,
            description: this.state.description,
            due_at: this.state.dueAt,
            done_at: this.state.doneAt,

            created_at: createdAt,
            updated_at: this.state.updatedAt,
        });

        new Alert(
            'Todo Created',
            'The todo successfully created, you can now go to the todos list and see your todos',
            'Ok',
            'success'
        ).make().show();
    }

    getDateTimeAsInputValue(date){
        return date.toISOString();
    }

    onChangeTitle(e){
        this.setState({
            title: e.target.value
        });
    }

    onChangeDescription(e){
        this.setState({
            description: e.target.value
        });
    }

    onChangeDue(e){
        let date = new Date();
        date.setTime(new Date(e.target.value).getTime());
        this.setState({
            dueAt: date
        });
    }

    getDateAsInputLocalDateTime(date){
        return date.toLocaleString('swe');
    }

    render(){
        return (
            <div className="form-box">
                <p className="form-title">Create A Todo !</p>
                <label htmlFor="title">Todo's Title</label>
                <input id="title" class="title" placeholder="Pass your title" value={this.state.title} onChange={this.onChangeTitle.bind(this)}/>

                <label htmlFor="description">Todo's description</label>
                <input id="description" class="description" placeholder="Pass your description" value={this.state.description} onChange={this.onChangeDescription.bind(this)}/>

                <label htmlFor="due">Todo's Due Date & Time</label>
                <input id="due" type="datetime-local" class="due" value={this.getDateAsInputLocalDateTime(new Date(this.state.dueAt))} onChange={this.onChangeDue.bind(this)}/>

                <div class="submit" onClick={this.createTodo.bind(this)}>
                    <p>Create Todo</p>
                    <TodoFormCreateSubmitLogo class="submit-logo"/>
                </div>
            </div>
        );
    }
}
